
--CREATE DATABASE KUTUPHANE;

use KUTUPHANE;

CREATE TABLE KITAP(
	kitap_ID INT IDENTITY(1,1) PRIMARY KEY,
	kitap_Adi VARCHAR(50) NOT NULL,
	sayfa_Sayisi INT NOT NULL,
	yazar_Id INT 
);

CREATE TABLE YAZAR(
	yazar_Id INT IDENTITY(1,1) PRIMARY KEY,
	yazar_Adi VARCHAR(50) NOT NULL,
	yazar_Soyadi VARCHAR(50) NOT NULL
);

ALTER TABLE KITAP
ADD CONSTRAINT FK_KitapYazar FOREIGN KEY (yazar_Id) REFERENCES YAZAR(yazar_Id);


ALTER TABLE KITAP ADD eklenme_Tarihi DATE DEFAULT GETDATE();

